// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Runescape_tracker.Database;

#nullable disable

namespace Runescape_tracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Runescape_tracker.Database.Fetch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FetchTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Fetches");
                });

            modelBuilder.Entity("Runescape_tracker.Database.SkillXp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.Property<int>("SkillsId")
                        .HasColumnType("integer");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SkillsId");

                    b.ToTable("SkillXp");
                });

            modelBuilder.Entity("Runescape_tracker.Database.Skills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FetchId")
                        .HasColumnType("integer");

                    b.Property<long>("TotalXp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FetchId")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Runescape_tracker.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Runescape_tracker.Database.Fetch", b =>
                {
                    b.HasOne("Runescape_tracker.Database.User", "User")
                        .WithMany("Fetches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Runescape_tracker.Database.SkillXp", b =>
                {
                    b.HasOne("Runescape_tracker.Database.Skills", "Skills")
                        .WithMany("SkillXpEntries")
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Runescape_tracker.Database.Skills", b =>
                {
                    b.HasOne("Runescape_tracker.Database.Fetch", "Fetch")
                        .WithOne("Skills")
                        .HasForeignKey("Runescape_tracker.Database.Skills", "FetchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fetch");
                });

            modelBuilder.Entity("Runescape_tracker.Database.Fetch", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Runescape_tracker.Database.Skills", b =>
                {
                    b.Navigation("SkillXpEntries");
                });

            modelBuilder.Entity("Runescape_tracker.Database.User", b =>
                {
                    b.Navigation("Fetches");
                });
#pragma warning restore 612, 618
        }
    }
}
